// Generated by cmc (check-my-code)
// Do not edit - regenerate with: cmc generate eslint

import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(js.configs.recommended, ...tseslint.configs.recommended, {
  rules: {
    "no-var": "error",
    "prefer-const": "error",
    eqeqeq: ["error", "always"],
  },
});
